export enum PageState {
    ADD_EXPENSE = "ADD_EXPENSE",
    ADD_INCOME = "ADD_INCOME",
    HOME = "HOME",
    TOP_SPEND_DETAILS = "TOP_SPEND_DETAILS",
    MONTHLY_SUMMARY = "MONTHLY_SUMMARY",
    INDIVIDUAL_EXPENDITURE = "INDIVIDUAL_EXPENDITURE",
    INDIVIDUAL_INCOME = "INDIVIDUAL_INCOME",
    MONTHLY_TOP_SPEND = "MONTHLY_TOP_SPEND",
}